#+title: Notes

* Character Selection Screen
** Notable Bytes
- $1B40: Player One selected character
- $1B80: Player Two selected character
- $5C-$5D: Current frame input player one
- $5E-$5F: Current frame input player two
- $60-$61: New button presses player one
- $62-$63: New button presses player two

** Character Codes
| Character | Value |
|-----------+-------|
| Moon      | $1    |
| Mercury   | $2    |
| Mars      | $3    |
| Jupiter   | $4    |
| Venus     | $5    |
| Uranus    | $6    |
| Neptune   | $7    |
| Pluto     | $8    |
| Chibi     | $9    |

** Notable Functions
- CSS_UPDATE_P1_CHAR
  On the CSS Screen, reads player one movement and sets the character code P1 is set to. Uses Character Selection Grid.
- C0EBFB handles sending audio data to APU.

* C0 Databanks
- Character Selection Grid
  Roughly C0AA51 - C0AA74
  4 byte chunks for each character. The chunks are:
  Up Down Left Right.

* Battle
** Notable Bytes
- 000a00 this seems to be one of several mirrored bytes that stores p1's position relative to the left side of the screen. $0 to $80
- $0803/$0804 contain the timer. It is in decimal, second then first
- $1001 seems to be p1 animation, changes based on frame but only when doing something goes up to 1300
  $0b00 looks worth looking into too
- $1d00 is p1 character, $1d03 is p2 character
  $1d02 is p1 character color
- At some point on load of scenes, 54 7f c0 6b 7f 7f 6b gets written to c8. this is a mvn opcode. :O 808dc9 writes to it on load. c01e83 on stage select
  MVN #$7F, #$C0
  RTL
  MVN #$7F, #$7F
  RTL

  JSR in instruction C3867c step over caused gong and tile viewer update
  83869A caused color palette update

  digging into one of the title screen updates, 80a23b is when we see it happen, but it was likely set before that as 80a21f onwards I see it manipulating data in $00 that I think it uses
  by the end of the function call at 80a278, it's updated the tileset to point at 4000 and is what we would expect it to look like. So The functions starting at 80a214 are our best bet to investigate further.

  - Potential breakpoints:
    83832E tiles load in this
    80A23B the start of the function where tiles load and then are corrected
    80A0DE top level, each time it runs we see a demo above and it reloads things
